openapi: 3.0.3
info:
  title: Api for WebLab4 definitions
  description: Api for WebLab4 definitions
  version: 1.0.0

paths: { }

components:
  schemas:
    AuthRequest:
      description: Auth request info (login, password)
      properties:
        login:
          description: login
          type: string
        password:
          description: password
          type: string
      required:
        - login
        - password

    ShotRequest:
      description: Shot request info
      properties:
        x:
          description: X coordinate
          type: number
        y:
          description: Y coordinate
          type: number
        radius:
          description: Plot radius
          type: number
        requestTime:
          '$ref': '#/components/schemas/DateTimeResponse'
      required:
        - x
        - y
        - radius
        - requestTime

    ShotTableResponse:
      description: List of shots
      type: object
      properties:
        shots:
          type: array
          items:
            '$ref': '#/components/schemas/ShotResponse'
      required:
        - shots

    ShotResponse:
      description: Shot response info
      properties:
        x:
          description: X coordinate
          type: number
        y:
          description: Y coordinate
          type: number
        radius:
          description: Plot radius
          type: number
        requestTime:
          '$ref': '#/components/schemas/DateTimeResponse'
        hit:
          description: Was hit
          type: boolean
      required:
        - x
        - y
        - radius
        - requestTime
        - hit

    DateTimeResponse:
      description: DateTime in ISO 8601 format
      type: string
      format: date-time
      example: '2023-01-28T13:18:28.372123Z'
      x-json-pattern: yyyy-MM-dd'T'HH:mm:ss.SSSSSSXXX
      x-default-timezone: UTC
