version: '3.9'

services:
  web-app:
    container_name: webapp4
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9900:9900'
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=admin

  db:
    container_name: db_webapp4
    image: postgres:14.0-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=admin

  pgadmin:
    container_name: pdadmin_webapp4
    image: dpage/pgadmin4:5.2
    restart: always
    ports:
      - '7080:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=arslan@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_PORT=80